scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 5s
    static_configs:
      - targets: ['otel-collector:8889']
      - targets: ['otel-collector:8888']
  # - job_name: 'custom'
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: 
  #       # - 'localhost:9090'
  #       - 'host.docker.internal:5101'