name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)_$(Rev:r)

trigger:
  - main
schedules:
  - cron: 0 22 * * *
    displayName: Daily nightly build
    branches:
      include:
        - main

variables:
  - name: Agent.Source.Git.ShallowFetchDepth
    value: '1'      

stages:
- template: build-stages-template.yaml
- template: deploy-stages-template.yaml