stages:
  - stage: Development
    displayName: 'Deploy to Development'
    dependsOn: Build
    condition: succeeded()

    jobs:
    - deployment: Deploy
      displayName: 'Deploy'
      environment: 'devopsworkshop-dev'

      pool:
        vmImage: 'windows-latest'
      
      strategy:
        runOnce:
          deploy:
            steps:

            - download: current
              displayName: 'download artifact'
              artifact: drop

            - task: AzureWebApp@1
              displayName: 'Deploy Azure Web App'
              inputs:
                azureSubscription: 'devopsworkshop-dev'
                appType: webApp
                appName: 'app-devopsworkshop-dev'
                package: '$(Pipeline.Workspace)/**/WebApi.zip'