name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)_$(Rev:r)

trigger: none

variables:
  - name: Agent.Source.Git.ShallowFetchDepth
    value: '1'

stages:
- template: build-stages-template.yaml

